# Generated by Django 4.0.1 on 2022-01-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_remove_reg_table_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_table',
            old_name='user_name',
            new_name='confirm_password',
        ),
        migrations.AddField(
            model_name='reg_table',
            name='first_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reg_table',
            name='last_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
