# Generated by Django 4.0.1 on 2022-01-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_rename_user_name_reg_table_confirm_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_table',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='reg_table',
            name='last_name',
        ),
        migrations.AddField(
            model_name='reg_table',
            name='email_id',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
